apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: openbao
  namespace: netbox
spec:
  provider:
    vault:
      server: http://openbao.openbao.svc.cluster.local:8200
      path: secret
      version: v2
      namespace: netbox
      auth:
        kubernetes:
          mountPath: kubernetes
          role: netbox-secret-sync
          serviceAccountRef:
            name: netbox-secret-sync
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-secrets
  namespace: netbox
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: netbox-secrets
    creationPolicy: Owner
    template:
      data:
        username: admin
        email: admin@famillelebreuil.net
  data:
    - secretKey: secret_key
      remoteRef:
        key: config
        property: secret-key
    - secretKey: password
      remoteRef:
        key: config
        property: superuser-password
    - secretKey: api_token
      remoteRef:
        key: config
        property: superuser-api-token
    - secretKey: email-password
      remoteRef:
        key: config
        property: email-password
    - secretKey: valkey-password
      remoteRef:
        key: config
        property: valkey-password
