apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: openbao
  namespace: netbox
spec:
  provider:
    vault:
      server: https://openbao.famillelebreuil.net
      path: secret
      version: v2
      namespace: netbox
      auth:
        kubernetes:
          mountPath: kubernetes
          role: netbox-secret-sync
          serviceAccountRef:
            name: netbox-secret-sync
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-secrets
  namespace: netbox
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: netbox-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: config
